// Auto-generated from All Mission Maps.txt
// Used by runtime validator to warn about missing/mismatched map filenames.

const ALL_MISSION_MAPS = [
  "A Bad Feeling.png",
  "A Balanced Harvest.png",
  "A First Foothold part 2.png",
  "A First Foothold part 3.png",
  "A First Foothold part 4.png",
  "A First Foothold.png",
  "A New Type of Plant.png",
  "A Prime Specimen.jpeg",
  "A Reveal in Ruins.jpeg",
  "A Symbol of Unification.png",
  "A Toxic Trail.png",
  "A Warm Place part 2.png",
  "A Warm Place.png",
  "After Rain Comes.png",
  "Armored Transports part 2.png",
  "Armored Transports part 3.png",
  "Armored Transports.png",
  "Back on Top part 2.png",
  "Back on Top part 3.png",
  "Back on Top part 4.png",
  "Back on Top.png",
  "Bees!.jpg",
  "Better Use.png",
  "Bombing Run.png",
  "Broken Monument.png",
  "Building a Library.png",
  "Celeste's Journal part 2.png",
  "Celeste's Journal.png",
  "Cold Storage part 1.png",
  "Cold Storage part 2.png",
  "Combat Recon part 2.png",
  "Combat Recon part 3.png",
  "Combat Recon.png",
  "Communication Hideout.png",
  "Deciphering the Data part 2.png",
  "Deciphering the Data.png",
  "Digging Up Dirt.png",
  "Doctor's Orders.png",
  "Dormant Baron part 2.png",
  "Dormant Baron.png",
  "Down to Earth.png",
  "Echoes of Victory Ridge.png",
  "Espresso.png",
  "Eyes in The Sky part 2.png",
  "Eyes in The Sky.png",
  "Eyes on the Prize.png",
  "Flickering Threat.png",
  "Greasing Her Palms part 2.png",
  "Greasing Her Palms part 3.png",
  "Greasing Her Palms.png",
  "Groundbreaking.png",
  "Hatch Repairs.png",
  "In My Image.png",
  "Industrial Espionage.png",
  "Into the Fray.png",
  "Keeping the Memory.png",
  "Lay of the Land part 2.png",
  "Lay of the Land.png",
  "Life of a Pharmacist.png",
  "Lost in Transmission.png",
  "Marked for Death.png",
  "Market Correction.png",
  "Medical Merchandise part 2.png",
  "Medical Merchandise.png",
  "Movie Night.png",
  "Off-The-Radar.png",
  "On Deaf Ears part 2.png",
  "On Deaf Ears part 3.png",
  "On Deaf Ears part 4.png",
  "On Deaf Ears.png",
  "Our Presence Up There.png",
  "Out of the Shadows.png",
  "Paving the Way part 2.png",
  "Paving the Way.png",
  "Picking Up the Pieces.png",
  "Power Out.jpg",
  "Prescriptions of the Past.png",
  "Reduced to Rubble part 2.png",
  "Reduced to Rubble.png",
  "Safe Passage.png",
  "Snap and Salvage part 2.png",
  "Snap and Salvage part 3.png",
  "Snap and Salvage part 4.png",
  "Snap and Salvage part 5.png",
  "Snap and Salvage part 6.png",
  "Snap and Salvage.png",
  "Source of the Contamination.png",
  "Sparks Fly.png",
  "Straight Record.png",
  "Switching the Supply.png",
  "The Clean Dream.png",
  "The League part 2.png",
  "The League.png",
  "The Major's Footlocker part 2.png",
  "The Major's Footlocker.png",
  "The Right Tool part 2.png",
  "The Right Tool part 3.png",
  "The Right Tool.png",
  "The Root of the Matter part 2.jpg",
  "The Root of the Matter.png",
  "The Stench of Corruption part 2.png",
  "The Stench of Corruption part 3.png",
  "The Stench of Corruption.png",
  "Trash Into Treasure.png",
  "Tribute to Toledo.png",
  "Trifecta Quest.png",
  "Turnabout.png",
  "Unexpected Initiatives part 2.png",
  "Unexpected Initiatives.png",
  "Untended Garden.png",
  "Water Troubles.png",
  "What Goes Around.png",
  "What We Left Behind part 2.png",
  "What We Left Behind part 3.png",
  "What We Left Behind.png",
  "With A Trace.png",
  "With a View.png"
];
